# SOURCE: https://circleci.com/docs/2.0/browser-testing/
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  build:
    docker:
      - image: cimg/node:18.3.0-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: mkdir test-reports
#      - run:
#          name: Install pip & selenium library
#          command: |
#            sudo apt-get update && sudo apt -y upgrade
#            sudo apt install -y python3-pip
#            sudo python3 -m pip install robotframework-seleniumlibrary
#            echo "robot selenium library installed"

      - run: |
          node --version
          java --version
          google-chrome --version
          python3 --version
          pip --version